version: '3'
services: 
    app:
        container_name: docker-node-mongo-chat
        restart: always
        build: .
        environment: 
            - PORT=3000
            - MONGODB_URL=mongodb://mongo:27017/node-chat-app-database-docker
        ports: 
            - '3000:3000'
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'
    
    nginx:
        container_name: webserver-nginx
        image: nginx:mainline-alpine
        ports:
            - "80:80"
        volumes: 
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - app